# Generated by Django 6.1.1 on 2026-10-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_basicinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='email',
        ),
    ]
